/*
 * generated by Xtext
 */
package org.eclipse.fx.code.editor.ldef.ui.contentassist

import org.eclipse.fx.code.editor.ldef.ui.contentassist.AbstractLDefProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LDefProposalProvider extends AbstractLDefProposalProvider {
}
