/*
 * generated by Xtext
 */
package org.eclipse.fx.code.compensator.hsl.ui.contentassist

import org.eclipse.fx.code.compensator.hsl.ui.contentassist.AbstractHSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HSLProposalProvider extends AbstractHSLProposalProvider {
}
