/*
 * generated by Xtext
 */
package org.eclipse.fx.code.editor.ldef.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LDefUiModule extends org.eclipse.fx.code.editor.ldef.ui.AbstractLDefUiModule {
	public LDefUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
