/*
 * generated by Xtext
 */
package org.eclipse.fx.code.compensator.hsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HSLUiModule extends org.eclipse.fx.code.compensator.hsl.ui.AbstractHSLUiModule {
	public HSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
