/*
 * generated by Xtext
 */
package org.eclipse.fx.code.editor.ldef;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LDefRuntimeModule extends org.eclipse.fx.code.editor.ldef.AbstractLDefRuntimeModule {

}
