/*
 * generated by Xtext
 */
package org.eclipse.fx.code.editor.ldef;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LDefStandaloneSetup extends LDefStandaloneSetupGenerated{

	public static void doSetup() {
		new LDefStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

