/*
* generated by Xtext
*/
package org.eclipse.fx.code.compensator.hsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.fx.code.compensator.hsl.ui.internal.HSLActivator.getInstance().getInjector("org.eclipse.fx.code.compensator.hsl.HSL");
	}
	
}
