/*******************************************************************************
 * Copyright (c) 2022 BestSolution.at and others.
 *  
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v.2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0.
 *  
 * SPDX-License-Identifier: EPL-2.0
 *  
 * Contributors:
 *     BestSolution.at - initial API and implementation
 *******************************************************************************/
/*
* generated by Xtext
*/
package org.eclipse.fx.code.compensator.hsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.fx.code.compensator.hsl.ui.internal.HSLActivator.getInstance().getInjector("org.eclipse.fx.code.compensator.hsl.HSL");
	}
	
}
