/*
 * generated by Xtext
 */
package org.eclipse.fx.code.compensator.hsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractHSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.eclipse.fx.code.compensator.hsl.hSL.HSLPackage.eINSTANCE);
		return result;
	}
}
