/*
 * generated by Xtext 2.9.0.v201505180813
 */
package org.eclipse.fx.xtext.statemachine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatemachineRuntimeModule extends org.eclipse.fx.xtext.statemachine.AbstractStatemachineRuntimeModule {

}
