/*******************************************************************************
 * Copyright (c) 2022 BestSolution.at and others.
 *  
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v.2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0.
 *  
 * SPDX-License-Identifier: EPL-2.0
 *  
 * Contributors:
 *     BestSolution.at - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext 2.9.0.v201505180813
 */
package org.eclipse.fx.xtext.statemachine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatemachineRuntimeModule extends org.eclipse.fx.xtext.statemachine.AbstractStatemachineRuntimeModule {

}
