/*
 * generated by Xtext
 */
package org.eclipse.fx.code.editor.ldef.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.fx.code.editor.ldef.services.LDefGrammarAccess;

public class LDefParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LDefGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.fx.code.editor.ldef.parser.antlr.internal.InternalLDefParser createParser(XtextTokenStream stream) {
		return new org.eclipse.fx.code.editor.ldef.parser.antlr.internal.InternalLDefParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}
	
	public LDefGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LDefGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
