/*
 * generated by Xtext
 */
package org.eclipse.fx.code.editor.ldef.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LDefAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/fx/code/editor/ldef/parser/antlr/internal/InternalLDef.tokens");
	}
}
