/*
 * generated by Xtext
 */
package org.eclipse.fx.code.editor.ldef;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LDefUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.eclipse.fx.code.editor.ldef.ui.internal.LDefActivator.getInstance().getInjector("org.eclipse.fx.code.editor.ldef.LDef");
	}
	
}
