/*
* generated by Xtext
*/
package org.eclipse.fx.code.compensator.hsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/fx/code/compensator/hsl/parser/antlr/internal/InternalHSL.tokens");
	}
}
