/*
 * generated by Xtext
 */
package org.eclipse.fx.code.compensator.hsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HSLRuntimeModule extends org.eclipse.fx.code.compensator.hsl.AbstractHSLRuntimeModule {

}
