/*
* generated by Xtext
*/
package org.eclipse.fx.code.compensator.hsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HSLStandaloneSetup extends HSLStandaloneSetupGenerated{

	public static void doSetup() {
		new HSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

